bookers2/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home/about' => 'homes#about', as: 'about'

  resources :users

  root to: 'homes#top'
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :book_id, uniqueness: {scope: :user_id}


end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}



  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_inactive_sign_up_path_for(resource)
    flash[:notice] = "successfully."
    user_path(current_user.id)
  end


  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end

end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController


  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end



end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user.id)

    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_common.html.erb
<!--共通部分用-->
<div class="col-md-3">
  <h2>User info</h2>

  <%= image_tag user.get_profile_image(100,100) %>
  <table class="mb-3 btn-block">
    <tbody>
      <tr></tr>
      <tr class="border-top">
        <th class="p-3">name</th>
        <th class="p-3"><%= user.name %></th>
      </tr>
      <tr class="border-top">
        <th class="p-3">introduction</th>
        <th class="p-3"><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block"  do %>
          <i class="fas fa-user-cog"></i>
      <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <% if book.errors.any? %>
    <%= book.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: book_new do |f| %>
    <lable for="book_title">Title</lable>
    <div>
      <%= f.text_field :title %>
    </div>
    <lable for="book_opinion">Opinion</lable>
    <div>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit 'Create Book', class: "bg-success text-white" %>
    </div>
  <% end %>
</div>

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <% if @book.errors.count == 1 %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
        <% else %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
        <% end %>

        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <div>
            <%= f.text_field :title, class: "btn-block" %>
          </div>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <div>
            <%= f.text_area :body, class: "btn-block" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "bg-success text-white" %>
        </div>
        <%= link_to "Show", book_path %>
        |
        <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'common', user: @user, book: @book, book_new: @book %>


    <!--ここからbook一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Book</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th style="width: 10%"></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to image_tag(book.user.get_profile_image(80,80)),user_path(book.user.id) %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <p><%= book.title %></p>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete do %>
                      <i class="fa-solid fa-heart" style="color:red"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>
                  コメント数：<%= book.book_comments.count %>
                </p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <%= render 'common', user: @book.user, book: @book, book_new: @book_new %>


    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <p><%= link_to image_tag(@book.user.get_profile_image(100,100)),user_path(@book.user.id) %></p>
              <p><%= link_to @book.user.name, user_path(@book.user.id) %></p>
            </td>
            <td>
              <p><%= link_to @book.title, user_path(@book.user.id) %></p>
            </td>
            <td>
              <p><%= @book.body %></p>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-outline-secondary bg-success text-white" %>
              <% end %>
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :delete do %>
                    <i class="fa-solid fa-heart" style="color:red"></i><%= @book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(@book), method: :post do %>
                    <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？",class: "btn btn-outline-secondary bg-danger text-white" %>
              <% end %>
            </td>
            <td>
              <p>コメント数：<%= @book.book_comments.count %></p>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
        <% @book.book_comments.each do |book_comment| %>
          <p>
            <%= image_tag book_comment.user.get_profile_image(80,80) %>
            <%= book_comment.user.name %>
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete, class: "btn btn-outline-secondary bg-danger text-white" %>
            <% end %>
          </p>
          <%= book_comment.comment %>
        <% end %>
      </div>

      <div>
        <%= form_with model: [@book,@book_comment] do |f| %>
          <div>
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "w-100" %>
          </div>
          <div>
            <%= f.submit "送信" %>
          </div>
        <% end %>

      </div>


    </div>
  </div>
</div>

bookers2/app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
        Welcome to
        <strong><i class="fas fa-solid fa-book"></i>Bookers</strong>
        !
    </h1>
  </div>
</div>

bookers2/app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <strong><i class="fas fa-solid fa-book"></i>Bookers</strong>!!</h1>
      <p>In <strong><i class="fa-solid fa-book"></i>Bookers</strong>,</p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <script src="https://kit.fontawesome.com/955a1400ea.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="navbar-brand p-3　navbar-nav nav-link ">
            <%= link_to 'Bookers', root_path, class: "text-white" %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="ture" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-home"></i>
                  <%= link_to 'Home', user_path(current_user.id), class: "text-white"   %>
                </li>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-users"></i>
                  <%= link_to 'Users', users_path, class: "text-white"  %>
                  <!--ここは後でユーザ一覧に変える-->
                </li>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-book-open"></i>
                  <%= link_to 'Books', books_path, class: "text-white"  %>
                </li>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-sign-out-alt"></i>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-white"  %>
                </li>
              <% else %>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-home"></i>
                  <%= link_to "Home", root_path, class: "text-white"  %>
                </li>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-link"></i>
                  <%= link_to "About", about_path, class: "text-white"  %>
                </li>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-user-plus"></i>
                  <%= link_to "Sign up", new_user_registration_path, class: "text-white"  %>
                </li>
                <li class="nav-item nav-link">
                  <i class="fas fa-solid fa-sign-in-alt"></i>
                  <%= link_to "Log in", new_user_session_path, class: "text-white"  %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p class="index-notice"><%= notice %></p>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

bookers2/app/views/users/_common2.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="mb-3">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <% if book_new.errors.any? %>
    <%= book_new.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: book do |f| %>
    <lable for="book_title">Title</lable>
    <div>
      <%= f.text_field :title %>
    </div>
    <lable for="book_opinion">Opinion</lable>
    <div>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit 'Create Book', class: "bg-success text-white" %>
    </div>
  <% end %>
</div>

bookers2/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>

        <%= @user.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>



      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <div>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "btn-block"%>
          </div>
        </div>
        <div class="form-group">
          <label for="inputImage">ProfileImage</label>
          <div>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
        </div>
        <div class="form-group">
          <label for="inputIntro">Introduction</label>
          <div>
            <%= f.text_area :introduction, id:"inputIntro", class: "btn-block" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "bg-secondary text-white" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<p class="index-notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'common2', user: @user, book: @book, book_new: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th style="width: 33%">image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <p><%= image_tag user.get_profile_image(80,80) %></p>
              </td>
              <td>
                <p><%= user.name %></p>
              </td>
              <td>
                <%= link_to 'Show', user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'common2', user: @user, book: @book_new, book_new: @book_new %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to image_tag(@user.get_profile_image(80,80)), user_path(@user.id) %>
            </td>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <%= book.body %>
            </td>
            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart" style="color:red"></i><%= book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              <p>コメント数：<%= book.book_comments.count %></p>
            </td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>