bookers/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'homes#top'
  root to: 'homes#top'

  get 'books' => 'books#index', as: 'index_book'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    # 最終的には専用の画面に移行する
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/views/books/edit.html.erb
<h1 class="edit-h1">Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<%= form_with model: @book, url: update_book_path(@book.id),method: :patch do |f| %>
  <label>Title</label>
  <div class="edit-box"><%= f.text_field :title %></div>

  <label>Body</label>
  <div class="edit-box"><%= f.text_area :body %></div>

  <p>
    <%= f.submit 'Update Book' %>
  </p>

  <p>
    <%= link_to "Show",book_path(@book.id) %>
    |
    <a href="/books">Back</a>
  </p>
<% end %>

bookers/app/views/books/index.html.erb
<p class="index-notice"><%= notice %></p>
<h1 class="index-h1">Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tbody>
    <tr>
      <td>
        <%= book.title %>
      </td>
      <td>
        <%= book.body %>
      </td>
      <td>
        <%= link_to "Show", book_path(book.id) %>
      </td>
      <td>
        <%= link_to "Edit", edit_book_path(book.id) %>
      </td>
      <td>
        <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>


<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <p>
    <%= f.submit 'Create Book' %>
  </p>
<% end %>

bookers/app/views/books/new.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>



<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <div class="success">
    <%= flash[:notice] %>
  </div>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>
<% end %>

bookers/app/views/books/show.html.erb
<p class="notice-1"><%= notice %></p>
<h2 class="created"><strong>Title:</strong> <%= @book.title %></h2>

<h2 class="created"><strong>Body:</strong> <%= @book.body %></h2>

<p>
<%= link_to "Edit",edit_book_path(@book.id) %>
|
<a href="/books">Back</a>
</p>

bookers/app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong>へ！</h1>

<p class='top1'><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p class='top1'>印象を共有し交換することができます</p>

<p class='top1'>
  <%= link_to "start", "/books" %>
</p>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>